

services:
  backend:
    build: ../backend
    env_file:
      - ../backend/.env

    ports:
      - '3000:3000'
    volumes:
      - ../backend:/app
    working_dir: /app
    command: npm run start:dev
    depends_on:
      - db



  frontend:
    build: ../frontend
    ports:
      - '5173:80'
    container_name: housebills-frontend
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: housebills-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: housebills
    ports:
      - '5432:5432'
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: