version: '3.8'

services:
  backend:
    build: ../backend
    ports:
      - '3000:3000'
    volumes:
      - ../backend:/app
    working_dir: /app
    command: npm run start:dev


  frontend:
    build: ../frontend
    ports:
      - '5173:80'
    container_name: housebills-frontend
    depends_on:
      - backend